{% set name = "dask-geomodeling" %}
{% set version = "2.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d22fce1a7591a36f5f359c660e7e90c220ceb626f42cc769288ddd8c2f281ad7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dask-core >=0.20
    - geopandas >=0.7
    - numpy >=1.14
    - pandas >=0.23
    - python >=3.6
    - pytz
    - scipy >=1.1

test:
  imports:
    - dask_geomodeling
    - dask_geomodeling.core
    - dask_geomodeling.geometry
    - dask_geomodeling.raster
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/nens/dask-geomodeling
  license: BSD-3-Clause
  license_file: LICENSE
  summary: On-the-fly operations on geographical maps
  description: |
    dsk-geomodeling is a collection of classes that are to be stacked together to
    create configurations for on-the-fly operations on geographical maps.
  doc_url: http://dask-geomodeling.readthedocs.io/
  dev_url: http://github.com/nens/dask-geomodeling

extra:
  recipe-maintainers:
    - caspervdw
    - reinout
