travis:
  secure:
    BINSTAR_TOKEN: nUL8DrEGscgUEikF6Ka/xZvy8z/xuiXm1D45QP1WwY1qpUbj+i4ZKEi3jQ7imiMSw5XqW263VHKOzkpmOIdOgCE/Tgh+bUpqX+9DSzpjQJLtNfoxglqKlTS5ounvEqEOJF0uJTrimuEUL6lCl+SkdSfaUu1EHBg0ZPhSqRssapoCX1FPLEoq6B/MmMbOX0CCSthDKRv9gnFQjTURbcST2qDb3lmzeW6P+t9+Sd2lztD2Tr8uEllkQYvi8rqMFuYH3vVcfIaimZDUXmQ1BMx/RufXTpfSgr21XJO5M9HZt37JAFYSh0jWmZdWSWmNZnRb4BzUaHZZn90H3D6yIOEQp+qS9nN4KP+EXrvQVtjRcIEVESwXD3rfEz2jtNRlFUxt9eWlv56ZqNy511pxKISHb0Dy+s6iZ8w0k/BQkTN7xBfvMP9LvfoYOZlAzJhR+alhoSM8q2OyyGc8S89OewnOvWhLNwhy2T49N2qycMDnqD1JG0I2PUlh4dMqmuxdSHOUVbqBsgCFS9bCYsMvCALSpYaJqiroH0HzFFyDTEwLjDmfBmX3QOoX+/C6fmXBXTN2sophjcyIzSU1mm/LALBDxuSiMn4LqZaGVYw4RBpEg9iMdToYoQFXmhhpUwU+LWmkE6vqcI7gG0VKwCHjdWLNHRvWCtATJbOIhm4MWD65fOM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
